#!/usr/bin/env ruby

require 'json'

SECONDS_IN_A_DAY = 86400

dir_name = "./records"
file_name = ARGV[0]
file_path = "#{dir_name}/#{file_name}.json"
action = ARGV[1]

if !Dir.exist?(dir_name) then Dir.mkdir(dir_name) end

if file_name then
  if !File.exist?(file_path) || File.empty?(file_path) then File.write(file_path, [].to_json) end

  existing_records = JSON.parse(File.read(file_path))

  if action === "today" then
    record = Time.now
    File.write(file_path, (existing_records.unshift(record)).to_json)
  else
    puts ((Time.now - Time.new(existing_records.first)) / SECONDS_IN_A_DAY).floor
  end
else
  Dir.each_child(dir_name) { |child| puts '- ' + child.split('.')[0] }
end
